"""add import job statistics

Revision ID: 00a972be9e4c
Revises: d66a9cb59559
Create Date: 2026-06-02 11:28:29.037659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a972be9e4c'
down_revision: Union[str, Sequence[str], None] = 'd66a9cb59559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('orders_created', sa.Integer(), nullable=False))
    op.add_column('import_jobs', sa.Column('orders_updated', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'orders_updated')
    op.drop_column('import_jobs', 'orders_created')
    # ### end Alembic commands ###
